"""Release-plan guards for multi-root verification and batch refresh."""

from __future__ import annotations


def extend_batch_review_rules(
    coverage: dict[str, tuple[str, ...]],
) -> None:
    """Require batch safety contracts at their owner and consumer versions."""
    additions = {
        "v0.16.0": (
            "`UntrustedMonotonicCorrelationCandidate`",
            "`AdmittedMonotonicDomainCorrelation`",
            "directed from one exact source",
            "`BorrowedHardBoundClaim`/`OwnedHardBoundClaim`",
            "`UnverifiedBoundDerivation` recipes",
            "exact paired capture anchors",
            "`CorrelationValidityCandidate` is non-circular",
            "`IndependentEndpointDeadlines { source, target }`",
            "correlation under admission",
            "acyclic-by-construction leaf set",
            "historical `AdmittedMonotonicDomainCorrelation` reference",
            "outward-rounded target",
            "conservative `earliest` edge",
            "permits direct translation only",
            "self-assert admission",
            "missing/truncated/substituted offset/rate/drift recipes",
        ),
        "v0.17.0": (
            "monotonic-correlation candidate audit",
            "immutable paired capture anchors",
            "without self-translation",
            "two-node/longer/replacement/restored-reference correlation",
        ),
        "v0.23.1": (
            "refresh reservations/fencing",
            "inherited live/tombstoned refresh reservations",
        ),
        "v0.24.0": (
            "correlation providers may emit only",
            "no admission method",
            "bounded derivation recipes/conditions",
            "exact paired capture",
            "narrow numeric assertion is not evidence",
        ),
        "v0.30.0": (
            "untrusted directed correlation candidates",
            "never admitted correlations",
            "exact cross-read anchors",
            "measured/configured/",
        ),
        "v0.37.0": (
            "`UntrustedMonotonicCorrelationCandidate`",
            "platform never admits",
            "bounded offset/rate/drift derivation roots",
        ),
        "v0.38.1": (
            "untrusted directed",
            "Cross-correlation tests cover direction",
        ),
        "v0.60.2": (
            "`AdmittedMonotonicDomainCorrelation` construction",
            "engine is the sole owner",
            "provider registration is only an",
            "`VerifiedBoundDerivation` and `PolicyAcceptedHardBound`",
            "snapshot-consistent `ConditionAssessment`",
            "transitive `SupportBasis`",
            "anchors/pairing generation",
            "`CorrelationValidity` initially accepts only independently checked",
            "Neither deadline may be translated",
            "circular validity",
            "acyclic by construction",
            "current, stale, replaced, or historical",
            "claim/assessment derived",
            "two-node or longer proof-support cycles",
            "correlation-on-correlation proof model",
        ),
        "v0.60.4": (
            "owned multi-root set",
            "Successful per-root proof/token identities",
            "BatchVerificationOutcome<T>",
            "BatchMemberId",
            "never caller order",
            "complete admitted membership",
            "shared derivation node is verified once",
            "Structural failure propagates",
            "root-specific evidence",
            "CompleteBatchVerification<T>",
            "CompleteMemberStatus<T>",
            "`Unprocessed` variant",
            "`AbortMemberDiagnostic`",
            "globally aborts the transaction",
            "`Unprocessed`",
            "exists only inside",
            "construct or convert",
            "original policy-defined `n`",
            "eligible interval contributor",
            "contribute no interval and no vote",
            "atomic installation of",
        ),
        "v0.60.5": (
            "`BatchAdmissionState<T>`",
            "`AdmissionValidity`",
            "It is explicitly not",
            "`IncompatibleMonotonicDomains`",
            "`PriorStateSubject`",
            "fixed-size `PriorStateObservation`",
            "PriorStateDisposition::{Retained, Invalidated, Absent}",
            "`LinearizationObservationStamp::{Measured, Unavailable}`",
            "`RefreshCoverageProfile::{LinearizationRefresh, CommitCoveredRefresh}`",
            "`LinearizationRefresh` is the portable default",
            "nonwrapping versioned",
            "`RefreshReservationGuard` binding reservation ID",
            "captured `RefreshInvalidationWatermark`",
            "`RefreshFencingGeneration`",
            "tombstones its reservation",
            "already-owned fixed reservation slot",
            "`Live` to `Tombstone`",
            "requires no allocation",
            "panic-capable cleanup",
            "`Drop` cannot return an error",
            "`SupersededTombstone`",
            "successful fenced no-op",
            "latches an engine invariant fault",
            "removes the old writer's install capability",
            "`Vacant`/`Live`/`Tombstone`/`SupersededTombstone`",
            "Slot saturation may reject new acquisition",
            "fallible/Pending-producing",
            "leaked/stalled live guard",
            "`SupersededNoInstall`",
            "process/session restart invalidates every inherited reservation",
            "reclaimed to `Vacant` only after",
            "counter or reclamation",
            "Arbitrary preemption may follow",
            "`RefreshInProgress`",
            "`CommitCoveredRefresh` is optional",
            "missing/stale remaining-work capability makes only",
            "`Unavailable(NoAuthorityObservationDomain)`",
            "cannot report `Retained` or install a new admission/",
            "at the refresh linearization point",
            "state identity/generation when present",
            "exact-domain",
            "unchanged prior",
            "invalidation generation and typed reason",
            "no authority through caller receipt",
            "older batch unchanged",
            "retiring the prior batch",
        ),
        "v0.61.0": (
            "consumes the matching `CompleteBatchVerification`",
            "`BatchAdmissionState` has no time-claim",
            "eligible interval contributors",
            "has no",
            "`AbortMemberDiagnostic`/`Unprocessed` input path",
            "`ConsensusAuthorityId`",
            "`ProofSupportSet`",
            "`AdmittedMonotonicDomainCorrelation`",
            "verified offset/rate/drift derivations",
            "transitive support bases, capture anchors",
            "retains and independently",
            "both endpoint `CorrelationValidity` deadlines",
            "no-transitive-correlation",
            "Alternative support requires",
        ),
        "v0.133.0": (
            "caller-filtered result iterators",
            "accepted-bound members contribute intervals/votes",
            "refused before orchestration",
            "preserves the exact `ConsensusAuthorityId`",
            "verified offset/rate/drift derivations",
        ),
        "v0.137.1": (
            "`PublishedAuthoritySnapshotId`",
            "PolicyAcceptedHardBound",
            "proof-support",
            "verified numerical derivations",
            "independent endpoint validity",
            "Publication independently rechecks both",
            "transitively backed by an admitted or historical correlation",
        ),
        "v0.137.2": (
            "retires the prior batch/snapshot",
            "`PriorStateObservation`",
            "`LinearizationRefresh` is required",
            "`RefreshInvalidationWatermark` and",
            "`RefreshFencingGeneration` storage",
            "elapsed time alone never does",
            "`SupersededNoInstall`",
            "preallocated reservation slot",
            "Cleanup consumes no secondary tombstone capacity",
            "Slot saturation rejects acquisition",
            "arbitrary post-sample",
            "`CommitCoveredRefresh`",
            "stale capability disables only this stronger profile",
            "arbitrary post-sample",
        ),
        "v0.137.5": ("no caller may use the report",),
        "v0.137.0": (
            "single-reader logical snapshot",
            "completed in `v0.137.5`",
        ),
        "v0.137.3": (
            "AdmittedLeapCandidate",
            "AdmittedEopSnapshot",
            "AdmittedScaleOffsetSnapshot",
            "atomically rechecks",
            "external scale-offset data",
            "single-thread transactional",
            "concurrent-reader",
        ),
        "v0.137.4": ("memory-ordering", "maximum read-latency"),
        "v0.137.6": ("target_has_atomic", "no silent emulation"),
        "v0.137.7": ("estimate_now()", "known-false future value"),
        "v0.138.0": (
            "refresh APIs return `PriorStateObservation`",
            "`LinearizationObservationStamp::{Measured,",
            "`RefreshCoverageProfile::{LinearizationRefresh,",
            "delayed blocking",
        ),
        "v0.139.0": (
            "authoritative prefix escapes",
            "`PriorStateObservation` is historical",
            "delayed waking/polling/return",
            "before requesting `RefreshReservationGuard`",
            "return `Poll::Pending`",
            "complete with `Poll::Ready`",
            "cannot store a live guard",
            "bounded in-place guard tombstone path",
        ),
        "v0.140.0": (
            "disjoint result buffers",
            "fixed-size",
            "canonical `ProofSupportSet`",
            "fencing/watermark generations",
            "correlation numerical derivations/conditions/",
            "reservation slots",
            "in-place state includes live/tombstone/superseded",
            "No separate tombstone capacity",
            "reader-generation tracking",
            "`CommitCoveredRefresh`",
            "cross-status construction",
        ),
        "v0.140.1": (
            "`CompleteMemberStatus`",
            "`AbortMemberDiagnostic`",
            "`Unprocessed` has no complete-witness encoding",
            "`AuthorityValidity`",
            "`PriorStateSubject`",
            "`BatchAdmissionState`",
            "`UntrustedMonotonicCorrelationCandidate`",
            "exact paired capture anchors/pairing generation",
            "cannot regain",
            "transitive correlation dependency",
            "`RefreshReservationGuard`",
            "bypass the in-place cleanup state machine",
            "recreates a live",
            "authorizes supersession",
            "`PublishedAuthoritySnapshotId`",
            "through-receipt authority claim",
        ),
        "v0.148.0": (
            "`BatchVerificationOutcome` complete/abort",
            "original-`n` membership accounting",
            "disjoint complete-member versus abort-diagnostic",
            "fixed-size measured/unavailable linearization observation",
            "exact bounded proof-support sets",
            "version-reserved `LinearizationRefresh`",
            "proof-bearing offset/rate/drift",
            "prohibition of",
            "transitive admitted/historical-correlation",
            "RAII guard/watermark/fencing/in-place",
            "in-place non-failing tombstone",
            "`CommitCoveredRefresh`",
        ),
        "v0.160.0": (
            "shared-node-once charging",
            "prior-state mutation",
            "separately bounded",
            "prior-observation variant",
            "admission/authority dependency",
            "correlation claim/recipe/condition/assessment/support/anchor",
            "no hidden correlation-DAG",
            "reservation-slot/reader-generation",
            "never cleanup",
            "bounded reclamation",
        ),
        "v0.161.0": (
            "`UntrustedMonotonicCorrelationCandidate`",
            "exact capture anchors",
            "bounded numerical claim recipes/conditions",
            "cannot smuggle",
            "no constructor,",
        ),
        "v0.163.0": (
            "batch/individual proof/token",
            "no-token global abort",
            "complete-membership witness enforcement",
            "compile-fail complete/abort status mixing",
            "original-`n`/no-vote enforcement",
            "prior retained/invalidated/absent outcomes",
            "immediate post-linearization expiry/invalidation",
            "prior identity/generation",
            "exact used `ProofSupportSet`",
            "unbounded post-sample hosted preemption",
            "reservation abandonment/leak/stall/ABA/",
            "forged narrow",
            "circular self/indirect validity",
            "A→B/B→A and longer proof-support cycles",
            "replacement-generation cycles",
            "restored historical-reference support",
            "guard panic/unwind/drop/cancellation",
            "in-place non-failing tombstone cleanup",
            "superseded-cleanup no-op",
            "impossible-transition fault",
            "allocation/callback/blocking/panic cleanup instrumentation",
            "timeout-steal refusal",
            "tombstone/reader-floor reclamation",
        ),
        "v0.164.0": (
            "version-reserved",
            "`LinearizationRefresh`",
            "`CommitCoveredRefresh`",
        ),
        "v0.166.0": (
            "`BatchVerificationOutcome`",
            "`AbortMemberDiagnostic`",
            "cannot reach a complete witness/quorum",
            "fixed-size `PriorStateObservation`",
            "`PriorStateDisposition::{Retained, Invalidated, Absent}`",
            "exact tagged admission/authority subject",
            "measured versus unavailable",
            "not authority",
            "proof-bearing offset/rate/drift claims",
            "no transitive admitted/historical-correlation",
            "`RefreshReservationGuard`",
            "allocation-free/non-panicking in-place cleanup",
            "engine-fault fallback",
            "no-`Poll::Pending` rule",
        ),
    }
    for version, phrases in additions.items():
        coverage[version] = coverage.get(version, ()) + phrases
