"""Release-plan guards for multi-root verification and batch refresh."""

from __future__ import annotations


def extend_batch_review_rules(
    coverage: dict[str, tuple[str, ...]],
) -> None:
    """Require batch safety contracts at their owner and consumer versions."""
    additions = {
        "v0.16.0": (
            "`UntrustedMonotonicCorrelationCandidate`",
            "`AdmittedMonotonicDomainCorrelation`",
            "directed from one exact source",
            "outward-rounded target",
            "conservative `earliest` edge",
            "permits direct translation only",
            "self-assert admission",
        ),
        "v0.24.0": (
            "correlation providers may emit only",
            "no admission method",
        ),
        "v0.30.0": (
            "untrusted directed correlation candidates",
            "never admitted correlations",
        ),
        "v0.37.0": (
            "`UntrustedMonotonicCorrelationCandidate`",
            "platform never admits",
        ),
        "v0.38.1": (
            "untrusted directed",
            "Cross-correlation tests cover direction",
        ),
        "v0.60.1": (
            "owned multi-root set",
            "individual proof/token identity equivalence",
            "BatchVerificationOutcome<T>",
            "BatchMemberId",
            "never caller order",
            "complete admitted membership",
            "shared derivation node is verified once",
            "Structural failure propagates",
            "root-specific evidence",
            "CompleteBatchVerification<T>",
            "CompleteMemberStatus<T>",
            "`Unprocessed` variant",
            "`AbortMemberDiagnostic`",
            "globally aborts the transaction",
            "`Unprocessed`",
            "exists only inside",
            "construct or convert",
            "original policy-defined `n`",
            "eligible interval contributor",
            "contribute no interval and no vote",
            "atomic installation of",
            "`BatchAdmissionState<T>`",
            "`AdmissionValidity`",
            "It is explicitly not",
            "`AdmittedMonotonicDomainCorrelation` construction",
            "engine is the sole owner",
            "`IncompatibleMonotonicDomains`",
            "`PriorStateSubject`",
            "fixed-size `PriorStateObservation`",
            "PriorStateDisposition::{Retained, Invalidated, Absent}",
            "`LinearizationObservationStamp::{Measured, Unavailable}`",
            "`RefreshCoverageProfile::{LinearizationRefresh, CommitCoveredRefresh}`",
            "`LinearizationRefresh` is the portable default",
            "nonwrapping versioned",
            "Arbitrary preemption may follow",
            "`RefreshInProgress`",
            "`CommitCoveredRefresh` is optional",
            "missing/stale remaining-work capability makes only",
            "`Unavailable(NoAuthorityObservationDomain)`",
            "cannot report `Retained` or install a new admission/",
            "at the refresh linearization point",
            "state identity/generation when present",
            "exact-domain",
            "unchanged prior",
            "invalidation generation and typed reason",
            "no authority through caller receipt",
            "older batch unchanged",
            "retiring the prior batch",
        ),
        "v0.61.0": (
            "consumes the matching `CompleteBatchVerification`",
            "`BatchAdmissionState` has no time-claim",
            "eligible interval contributors",
            "has no",
            "`AbortMemberDiagnostic`/`Unprocessed` input path",
            "`ConsensusAuthorityId`",
            "`ProofSupportSet`",
            "`AdmittedMonotonicDomainCorrelation`",
            "Alternative support requires",
        ),
        "v0.133.0": (
            "caller-filtered result iterators",
            "accepted-bound members contribute intervals/votes",
            "refused before orchestration",
            "preserves the exact `ConsensusAuthorityId`",
        ),
        "v0.137.1": (
            "retires the prior batch/snapshot",
            "`PriorStateObservation`",
            "`PublishedAuthoritySnapshotId`",
            "`LinearizationRefresh` is required",
            "arbitrary post-sample",
            "`CommitCoveredRefresh`",
            "stale capability disables only this stronger profile",
            "no caller may use the report",
        ),
        "v0.137.2": (
            "nonwrapping reservation/version",
            "`LinearizationRefresh`",
            "`CommitCoveredRefresh`",
            "unbounded post-sample preemption",
        ),
        "v0.138.0": (
            "refresh APIs return `PriorStateObservation`",
            "`LinearizationObservationStamp::{Measured,",
            "`RefreshCoverageProfile::{LinearizationRefresh,",
            "delayed blocking",
        ),
        "v0.139.0": (
            "authoritative prefix escapes",
            "`PriorStateObservation` is historical",
            "delayed waking/polling/return",
        ),
        "v0.140.0": (
            "disjoint result buffers",
            "fixed-size",
            "canonical `ProofSupportSet`",
            "version/reservation strategy",
            "`CommitCoveredRefresh`",
            "cross-status construction",
        ),
        "v0.140.1": (
            "`CompleteMemberStatus`",
            "`AbortMemberDiagnostic`",
            "`Unprocessed` has no complete-witness encoding",
            "`AuthorityValidity`",
            "`PriorStateSubject`",
            "`BatchAdmissionState`",
            "`UntrustedMonotonicCorrelationCandidate`",
            "`PublishedAuthoritySnapshotId`",
            "through-receipt authority claim",
        ),
        "v0.148.0": (
            "`BatchVerificationOutcome` complete/abort",
            "original-`n` membership accounting",
            "disjoint complete-member versus abort-diagnostic",
            "fixed-size measured/unavailable linearization observation",
            "exact bounded proof-support sets",
            "version-reserved `LinearizationRefresh`",
            "`CommitCoveredRefresh`",
        ),
        "v0.160.0": (
            "shared-node-once charging",
            "prior-state mutation",
            "separately bounded",
            "prior-observation variant",
            "admission/authority dependency",
        ),
        "v0.161.0": (
            "`UntrustedMonotonicCorrelationCandidate`",
            "no constructor or",
        ),
        "v0.163.0": (
            "batch/individual proof/token",
            "no-token global abort",
            "complete-membership witness enforcement",
            "compile-fail complete/abort status mixing",
            "original-`n`/no-vote enforcement",
            "prior retained/invalidated/absent outcomes",
            "immediate post-linearization expiry/invalidation",
            "prior identity/generation",
            "exact used `ProofSupportSet`",
            "unbounded post-sample hosted preemption",
            "reservation abandonment/ABA",
        ),
        "v0.164.0": (
            "version-reserved",
            "`LinearizationRefresh`",
            "`CommitCoveredRefresh`",
        ),
        "v0.166.0": (
            "`BatchVerificationOutcome`",
            "`AbortMemberDiagnostic`",
            "cannot reach a complete witness/quorum",
            "fixed-size `PriorStateObservation`",
            "`PriorStateDisposition::{Retained, Invalidated, Absent}`",
            "exact tagged admission/authority subject",
            "measured versus unavailable",
            "not authority",
        ),
    }
    for version, phrases in additions.items():
        coverage[version] = coverage.get(version, ()) + phrases
