"""Additional release-plan guards for runtime hard-bound assessment."""

from __future__ import annotations


def extend_runtime_review_rules(
    coverage: dict[str, tuple[str, ...]],
    forbidden: dict[str, tuple[str, ...]],
) -> None:
    """Add runtime-assessment coverage without bloating the main validator."""
    additions = {
        "v0.6.1": (
            "Canonical Identity Kernel",
            "CanonicalIdentityV1",
            "IdentityDigestV1 = SHA-256",
            "nist-fips-180-4-upd1",
            "commutative operations using",
            "structural comparison",
            "Rust `Hash`",
            "serde output",
            "forced-collision",
        ),
        "v0.7.1": (
            "UnverifiedBoundDerivation<T>",
            "ClaimOriginId",
            "DerivationHandle<'arena, T>",
            "DerivationArena",
            "fallible explicitly bounded arena",
            "generative lifetime brand",
            "checked nonwrapping store/node generations",
            "same-address reinitialization",
            "immutable read lease or frozen pinned snapshot",
            "not `Sync`",
            "`same_geometry()`",
            "`same_conditional_claim()`",
            "`try_same_derivation(left_lease, right_lease)`",
            "infallible semantic `Eq`/`Hash`",
            "canonical collision buckets",
            "heterogeneous recipe nodes",
            "Geometry-only",
            "complete reachable bounded canonical derivation",
            "recipe-drop/detachment refusal",
            "API/type size and stack-use",
        ),
        "v0.7.2": (
            "automatically composes",
            "recipe digests",
            "byte/storage",
            "cycle-detection",
            "digest-only claim",
            "Cross-store composition",
            "import/reinterning",
        ),
        "v0.7.3": (
            "UnverifiedBoundDerivationRecord",
            "non-authoritative core `UnverifiedBoundDerivation<T>`",
            "malformed/truncated/spliced derivation records",
            "not arena/store handles",
            "atomically interns",
        ),
        "v0.8.0": ("selected era", "recipe preservation"),
        "v0.9.0": ("UnverifiedBoundDerivation", "recipe quantum"),
        "v0.11.0": ("UnverifiedBoundDerivation", "claim-recipe loss"),
        "v0.11.1": ("UnverifiedBoundDerivation", "recipe tests replace EOP"),
        "v0.11.2": ("UnverifiedBoundDerivation", "complete recipe"),
        "v0.11.3": ("UnverifiedBoundDerivation", "recipe substitution"),
        "v0.11.4": ("UnverifiedBoundDerivation", "recipe substitution"),
        "v0.12.0": ("UnverifiedBoundDerivation", "recipe table/EOP"),
        "v0.13.0": (
            "UnverifiedBoundDerivation",
            "policy/profile/branch/model/recipe",
        ),
        "v0.14.0": (
            "UnverifiedBoundDerivation",
            "statistical-only recipe refusal",
        ),
        "v0.15.0": (
            "UnverifiedBoundDerivation",
            "transitive-recipe preservation",
        ),
        "v0.16.0": (
            "MonotonicReadInterval",
            "resolution/quantization",
            "operation-supplied completion margin",
            "upper-edge deadline comparisons",
        ),
        "v0.17.0": (
            "`CanonicalIdentityV1` preimage/domain-separation/schema-reuse",
            "differential/KAT review",
            "first-party SHA-256",
            "collision-bucket cache/interning",
            "lifetime-brand generativity",
            "same-address ABA resistance",
            "generation exhaustion",
            "eviction/read leases",
            "mutable/frozen/read-only `Send`/`Sync`",
            "fallible-derivation equality",
            "Kani-style reduced-state proofs",
            "no_std stack/code-size",
        ),
        "v0.22.1": (
            "UnverifiedBoundDerivationRecord",
            "no tag or decode",
            "`CanonicalIdentityV1`",
            "parallel serde-shaped",
            "no-second-encoding",
        ),
        "v0.24.0": (
            "read_interval() -> Result<MonotonicReadInterval",
            "measurement method",
            "scalar native counters are conservatively inflated",
            "LinearizationReadCapability",
            "ThroughCompletionCapability",
            "reviewed maximum completion/WCET",
        ),
        "v0.24.1": (
            "fixed public-data",
            "cannot replace its preimage",
            "identity-profile reproduction",
        ),
        "v0.30.0": (
            "hosted `read_interval()` implementations",
            "target-specific",
            "General-purpose hosted adapters",
            "do not claim `ThroughCompletionCapability`",
        ),
        "v0.37.0": (
            "bounded `MonotonicReadInterval`",
            "unsupported methods never collapse",
            "scalar-inflation",
        ),
        "v0.38.1": (
            "counter `read_interval()` strategies",
            "migration-ambiguous scalar read",
            "interval containment",
        ),
        "v0.38.2": (
            "caller-provided embedded monotonic clocks",
            "WCET-backed through-completion capability",
            "missing bounds",
        ),
        "v0.39.1": (
            "historical evidence only after restore",
            "UnverifiedBoundDerivationRecord",
            "has no direct `Deserialize`",
            "cross-engine copy",
            "complete bounded reachable canonical DAG",
            "handle/store/address leakage",
        ),
        "v0.60.1": (
            "Runtime Bound-Condition Assessment And Policy Admission",
            "ConditionAssessment",
            "Supported",
            "Contradicted",
            "Indeterminate",
            "Expired",
            "Withdrawn",
            "PolicyAcceptedHardBound<T>",
            "SupportBasis",
            "EvidenceOrigin",
            "IntegrityBasis",
            "AuthorityBasis",
            "complete bounded transitive leaf-basis",
            "configured-assumption origin",
            "VerifiedBoundDerivation<T>",
            "`UnverifiedBoundDerivation<T>`",
            "`DerivationHandle<'arena, T>`",
            "exact admitted arena brand/",
            "immutable read lease or frozen pinned snapshot",
            "releases all arena locks/leases",
            "concurrent eviction",
            "arena lock/lease",
            "geometry-only intervals",
            "root derivation binds",
            "rounding direction",
            "one snapshot-consistent transaction",
            "assessor-registry generation",
            "engine linearization point",
            "`MonotonicReadInterval`",
            "required upper edge reaches `valid_until`",
            "accepted-token identity/equivalence",
            "recipe digest alone cannot make",
            "accepted-token cache non-substitution",
            "verification work crossing expiry",
            "provider callbacks return structured evidence, not `is_true`",
            "adversarial interval narrowing",
            "no mixed or partial assessment/token",
            "downstream invalidation graph",
            "but no clock",
        ),
        "v0.61.0": (
            "PolicyAcceptedHardBound",
            "derivation identity, condition",
            "through explicit diagnostic",
        ),
        "v0.61.1": (
            "verified-bound-derivation",
            "support-basis report",
        ),
        "v0.133.0": (
            "PolicyAcceptedHardBound",
            "verified-derivation and assessment",
            "unmodified per-atom `SupportBasis`",
            "no servo or clock-publication authority",
        ),
        "v0.134.0": (
            "PolicyAcceptedHardBound",
            "verified-derivation or assessment",
        ),
        "v0.134.1": (
            "accepted-bound verified-derivation/assessment generations",
            "assessment expiry/stale token",
        ),
        "v0.134.3": (
            "PolicyAcceptedHardBound",
            "verified-derivation generations",
            "derivation or assessment",
        ),
        "v0.135.0": (
            "PolicyAcceptedHardBound",
            "derivation or assessment loss",
            "accepted-condition expiry/rejection",
        ),
        "v0.136.0": (
            "reassessed during holdover",
            "invalidated observation/model derivations",
            "stale accepted token",
        ),
        "v0.137.0": (
            "ConditionAssessment",
            "PolicyAcceptedHardBound",
            "verified-derivation identity",
            "default strict `TrustedClock::now()`",
            "LinearizedTrustedTime",
            "observed_at.latest < valid_until",
            "unknowably delayed caller-receipt",
            "`TrustedClock::now_through_completion()`",
            "ThroughCompletionCapability",
            "CompletionBoundTrustedTime",
            "General-purpose platforms",
            "suspend-inclusive monotonic domain",
            "timer starvation",
            "conditional-not-synchronized refusal",
        ),
        "v0.137.1": (
            "PolicyAcceptedHardBound",
            "verified derivation",
            "concurrent linearization-time strict read",
            "observed_at.latest < valid_until",
            "latest + wcet < valid_until",
            "WCET capability/generation",
            "cached pre-expiry label",
            "idle-expiry",
            "estimates publish only with explicit",
            "synchronized-to-",
        ),
        "v0.137.2": (
            "read_interval()",
            "through-completion capability",
            "reviewed bound",
            "WCET-capability",
        ),
        "v0.137.3": ("condition-assessment loss",),
        "v0.138.0": (
            "separate explicit result paths",
            "no `is_trusted` boolean",
            "exact per-atom `SupportBasis`",
            "verified-derivation status",
            "contracts type-distinct",
            "`observed_at` and",
            "`now_through_completion()`",
            "contract non-substitution",
            "conditional diagnostic preservation",
        ),
        "v0.140.0": (
            "derivation arena",
            "node/edge",
            "scoped generative-brand creation",
            "mutable/frozen/read-only state",
            "lease policy",
            "exhaustion behavior",
            "worst-case claim/handle size",
            "DAG sharing/exhaustion/eviction",
        ),
        "v0.140.1": (
            "historical evidence",
            "accepted-bound tokens",
            "UnverifiedBoundDerivationRecord",
            "no direct deserialize path",
            "cross-engine copy",
        ),
        "v0.142.0": (
            "PolicyAcceptedHardBound",
            "verified-derivation and condition-assessment",
            "derivation/assessment-loss",
        ),
        "v0.145.0": (
            "browser/Node monotonic adapters",
            "timer-resolution reduction",
            "never claim through-completion WCET",
            "event-loop starvation",
        ),
        "v0.148.0": (
            "ConditionAssessment",
            "PolicyAcceptedHardBound",
            "VerifiedBoundDerivation",
            "UnverifiedBoundDerivationRecord",
            "CanonicalIdentityV1",
            "typed arena handle",
            "provider-owned",
            "reviewed-WCET through-completion",
            "structured per-atom `SupportBasis`",
            "strict-versus-diagnostic facade behavior",
        ),
        "v0.163.0": (
            "runtime condition",
            "stale accepted-bound tokens",
            "canonical-identity cross-type",
            "forced digest collisions",
            "derivation-arena exhaustion",
            "missing/truncated/over-budget early recipes",
            "narrowed/spliced/substituted",
            "serialized-record replay/rollback/cross-engine restore",
            "transitive-basis laundering",
            "browser",
            "missing-bound refusal",
            "WCET-capability",
            "strict-facade synchronized-label",
        ),
        "v0.164.0": (
            "monotonic provider",
            "strict-authority",
            "through-completion",
            "complete return path",
        ),
        "v0.166.0": (
            "canonical identity preimages/algorithm/structural collision",
            "mandatory typed derivation handles",
            "provider-owned monotonic",
            "linearization-time `observed_at`/`valid_until`",
            "WCET-backed",
            "early non-authoritative derivation recipes",
            "restore type-state",
            "verified root/",
            "structured independent origin",
            "upper-edge deadline/domain enforcement",
            "no trusted boolean",
        ),
    }
    exclusions = {
        "v0.7.3": (
            "PolicyAcceptedHardBound",
            "ConditionAssessment",
            "VerifiedBoundDerivation",
        ),
        "v0.60.0": (
            "PolicyAcceptedHardBound",
            "ConditionAssessment",
            "VerifiedBoundDerivation",
            "SupportBasis",
        ),
    }
    for version, phrases in additions.items():
        coverage[version] = coverage.get(version, ()) + phrases
    for version, phrases in exclusions.items():
        forbidden[version] = forbidden.get(version, ()) + phrases
